package io.bdrc.lucene.bo.phonetics;

import java.util.HashMap;

public class PhoneticSystemEnglish extends PhoneticSystem {
    
    public boolean ignoreRetroflex = true;
    public boolean alntoeln = true;
    public boolean foldnasals = false;
    
    public void addOnset(final String onset, String phonetic, final boolean canbefinal) {
        if (this.ignoreRetroflex && phonetic.startsWith("D"))
            phonetic = "d";
        this.onsetTrie.add(onset,  phonetic, canbefinal);
    }
    
    public void addSkt(final char c, String sktPhonetic) {
        this.sktPhonetic.put(c, sktPhonetic);
    }
    
    public void addOnset(final String onset, final String phonetic) {
        this.addOnset(onset, phonetic, true);
    }
    
    public void addVowelCoda(final String vowelCoda, String phonetic) {
        if (phonetic.contains("ä")) {
            if (this.alntoeln)
                phonetic = phonetic.replace("ä", "e");
            else
                phonetic = phonetic.replace("ä", "a");
        }
        if (this.foldnasals) {
            phonetic = phonetic.replace("m", "n");
            phonetic = phonetic.replace("N", "n");
        }
        this.vowelCodaRoot.put(vowelCoda, phonetic.toCharArray());
    }
    
    public static final PhoneticSystemEnglish INSTANCE = new PhoneticSystemEnglish();
    
    public PhoneticSystemEnglish() {
        super("a");
        // we ignore tones, aspiration, voicing
        // gy = G
        // ng = N
        // ny = Y
        // dr = D
        // ts = T
        this.onsetTrie = new BasicTrie();
        this.addOnset("ཀ", "g");
        this.addOnset("ཀྱ", "G");
        this.addOnset("ཀྲ", "D");
        this.addOnset("ཀླ", "l");
        this.addOnset("དཀ", "g");
        this.addOnset("དཀྱ", "G");
        this.addOnset("དཀྲ", "D");
        this.addOnset("བཀ", "g");
        this.addOnset("བཀྱ", "G");
        this.addOnset("བཀྲ", "D");
        this.addOnset("བཀླ", "l");
        this.addOnset("རྐ", "g");
        this.addOnset("རྐྱ", "G");
        this.addOnset("ལྐ", "g");
        this.addOnset("སྐ", "g");
        this.addOnset("སྐྱ", "G");
        this.addOnset("སྐྲ", "D");
        this.addOnset("བརྐ", "g");
        this.addOnset("བརྐྱ", "G");
        this.addOnset("བསྐ", "g");
        this.addOnset("བསྐྱ", "G");
        this.addOnset("བསྐྲ", "D");
        this.addOnset("ཁ", "g");
        this.addOnset("ཁྱ", "G");
        this.addOnset("ཁྲ", "D");
        this.addOnset("མཁ", "g");
        this.addOnset("མཁྱ", "G");
        this.addOnset("མཁྲ", "D");
        this.addOnset("འཁ", "g");
        this.addOnset("འཁྱ", "G");
        this.addOnset("འཁྲ", "D");
        this.addOnset("ག", "g");
        this.addOnset("གྱ", "G");
        this.addOnset("གྲ", "D");
        this.addOnset("གླ", "l");
        this.addOnset("དག", "g", false);
        this.addOnset("དགྱ", "G");
        this.addOnset("དགྲ", "D");
        this.addOnset("བག", "g", false);
        this.addOnset("བགྱ", "G");
        this.addOnset("བགྲ", "D");
        this.addOnset("མག", "g", false);
        this.addOnset("མགྱ", "G");
        this.addOnset("མགྲ", "D");
        this.addOnset("འག", "g", false);
        this.addOnset("འགྱ", "G");
        this.addOnset("འགྲ", "D");
        this.addOnset("རྒ", "g");
        this.addOnset("རྒྱ", "G");
        this.addOnset("ལྒ", "g");
        this.addOnset("སྒ", "g");
        this.addOnset("སྒྱ", "G");
        this.addOnset("སྒྲ", "D");
        this.addOnset("བརྒ", "g");
        this.addOnset("བརྒྱ", "G");
        this.addOnset("བསྒ", "g");
        this.addOnset("བསྒྱ", "G");
        this.addOnset("བསྒྲ", "D");
        this.addOnset("ང", "N");
        this.addOnset("དང", "N", false);
        this.addOnset("མང", "N", false);
        this.addOnset("རྔ", "N");
        this.addOnset("ལྔ", "N");
        this.addOnset("སྔ", "N");
        this.addOnset("བརྔ", "N");
        this.addOnset("བསྔ", "N");
        this.addOnset("ཅ", "c");
        this.addOnset("གཅ", "c");
        this.addOnset("བཅ", "c");
        this.addOnset("ལྕ", "c");
        this.addOnset("ཆ", "c");
        this.addOnset("མཆ", "c");
        this.addOnset("འཆ", "c");
        this.addOnset("ཇ", "c");
        this.addOnset("མཇ", "c");
        this.addOnset("འཇ", "c");
        this.addOnset("རྗ", "c");
        this.addOnset("ལྗ", "c");
        this.addOnset("བརྗ", "c");
        this.addOnset("ཉ", "Y");
        this.addOnset("གཉ", "Y");
        this.addOnset("མཉ", "Y");
        this.addOnset("རྙ", "Y");
        this.addOnset("སྙ", "Y");
        this.addOnset("བརྙ", "Y");
        this.addOnset("བསྙ", "Y");
        this.addOnset("ཏ", "d");
        this.addOnset("གཏ", "d");
        this.addOnset("བཏ", "d");
        this.addOnset("རྟ", "d");
        this.addOnset("ལྟ", "d");
        this.addOnset("སྟ", "d");
        this.addOnset("བརྟ", "d");
        this.addOnset("བལྟ", "d");
        this.addOnset("བསྟ", "d");
        this.addOnset("ཐ", "d");
        this.addOnset("མཐ", "d");
        this.addOnset("འཐ", "d");
        this.addOnset("ད", "d");
        this.addOnset("དྲ", "D");
        this.addOnset("གད", "d", false);
        this.addOnset("བད", "d", false);
        this.addOnset("མད", "d", false);
        this.addOnset("འད", "d", false);
        this.addOnset("འདྲ", "D");
        this.addOnset("རྡ", "d");
        this.addOnset("ལྡ", "d");
        this.addOnset("སྡ", "d");
        this.addOnset("བརྡ", "d");
        this.addOnset("བལྡ", "d");
        this.addOnset("བསྡ", "d");
        this.addOnset("ན", "n");
        this.addOnset("གན", "n", false);
        this.addOnset("མན", "n", false);
        this.addOnset("རྣ", "n");
        this.addOnset("སྣ", "n");
        this.addOnset("བརྣ", "n");
        this.addOnset("བསྣ", "n");
        this.addOnset("པ", "b");
        this.addOnset("པྱ", "c");
        this.addOnset("པྲ", "D");
        this.addOnset("དཔ", "b");
        this.addOnset("དཔྱ", "c");
        this.addOnset("དཔྲ", "D");
        this.addOnset("ལྤ", "b");
        this.addOnset("སྤ", "b");
        this.addOnset("སྤྱ", "c");
        this.addOnset("སྤྲ", "D");
        this.addOnset("ཕ", "b");
        this.addOnset("ཕྱ", "c");
        this.addOnset("ཕྲ", "D");
        this.addOnset("འཕ", "b");
        this.addOnset("འཕྱ", "c");
        this.addOnset("འཕྲ", "D");
        this.addOnset("བ", "b");
        this.addOnset("བྱ", "c");
        this.addOnset("བྲ", "D");
        this.addOnset("བླ", "l");
        this.addOnset("དབ", "", false);
        this.addOnset("དབྱ", "y");
        this.addOnset("དབྲ", "r");
        this.addOnset("འབ", "b", false);
        this.addOnset("འབྱ", "c");
        this.addOnset("འབྲ", "D");
        this.addOnset("རྦ", "b");
        this.addOnset("ལྦ", "b");
        this.addOnset("སྦ", "b");
        this.addOnset("སྦྱ", "c");
        this.addOnset("སྦྲ", "D");
        this.addOnset("མ", "m");
        this.addOnset("མྱ", "Y");
        this.addOnset("དམ", "m", false);
        this.addOnset("དམྱ", "Y");
        this.addOnset("རྨ", "m");
        this.addOnset("རྨྱ", "Y");
        this.addOnset("སྨ", "m");
        this.addOnset("སྨྱ", "Y");
        this.addOnset("ཙ", "T");
        this.addOnset("གཙ", "T");
        this.addOnset("བཙ", "T");
        this.addOnset("རྩ", "T");
        this.addOnset("སྩ", "T");
        this.addOnset("བརྩ", "T");
        this.addOnset("བསྩ", "T");
        this.addOnset("ཚ", "T");
        this.addOnset("མཚ", "T");
        this.addOnset("འཚ", "T");
        this.addOnset("ཛ", "T");
        this.addOnset("མཛ", "T");
        this.addOnset("འཛ", "T");
        this.addOnset("རྫ", "T");
        this.addOnset("བརྫ", "T");
        this.addOnset("ཝ", "w");
        this.addOnset("ཞ", "S");
        this.addOnset("གཞ", "S");
        this.addOnset("བཞ", "S");
        this.addOnset("ཟ", "s");
        this.addOnset("ཟླ", "d");
        this.addOnset("གཟ", "s");
        this.addOnset("བཟ", "s");
        this.addOnset("བཟླ", "d");
        this.addOnset("འ", "");
        this.addOnset("ཡ", "y");
        this.addOnset("གཡ", "y");
        this.addOnset("ར", "r");
        this.addOnset("རླ", "l");
        this.addOnset("བརླ", "l");
        this.addOnset("ལ", "l");
        this.addOnset("ཤ", "S");
        this.addOnset("གཤ", "S");
        this.addOnset("བཤ", "S");
        this.addOnset("ས", "s");
        this.addOnset("སྲ", "s");
        this.addOnset("སླ", "l");
        this.addOnset("གས", "s", false);
        this.addOnset("བས", "s", false);
        this.addOnset("བསྲ", "s");
        this.addOnset("བསླ", "l");
        this.addOnset("ཧ", "h");
        this.addOnset("ཧྲ", "r");
        this.addOnset("ལྷ", "l");
        this.addOnset("ཨ", "");
        this.addOnset("བགླ", "l");
        this.addOnset("མྲ", "m");
        this.addOnset("སྨྲ", "m");
        this.addOnset("ཏྲ", "D");
        this.addOnset("བརྟ", "d");
        this.addOnset("ཐྲ", "D");
        this.addOnset("སྣྲ", "n");
        this.addOnset("ཀྭ", "g");
        this.addOnset("བཀྭ", "g");
        this.addOnset("ཁྭ", "g");
        this.addOnset("གྭ", "g");
        this.addOnset("གྲྭ", "D");
        this.addOnset("བཅྭ", "c");
        this.addOnset("ཉྭ", "Y");
        this.addOnset("ཏྭ", "d");
        this.addOnset("ཐྭ", "d");
        this.addOnset("དྭ", "d");
        this.addOnset("དྲྭ", "D");
        this.addOnset("ཕྱྭ", "c");
        this.addOnset("མྭ", "m");
        this.addOnset("ཙྭ", "T");
        this.addOnset("རྩྭ", "T");
        this.addOnset("ཚྭ", "T");
        this.addOnset("ཛྭ", "T");
        this.addOnset("ཞྭ", "S");
        this.addOnset("ཟྭ", "s");
        this.addOnset("རྭ", "r");
        this.addOnset("ལྭ", "l");
        this.addOnset("ལྷྭ", "l");
        this.addOnset("ཤྭ", "S");
        this.addOnset("སྟྭ", "d");
        this.addOnset("སྭ", "s");
        this.addOnset("བསྭ", "s");
        this.addOnset("ཧྭ", "h");
        
        this.vowelCodaRoot = new HashMap<>();
        this.addVowelCoda("", "a");
        this.addVowelCoda("འ", "a");
        this.addVowelCoda("ག", "ag");
        this.addVowelCoda("གས", "ag");
        this.addVowelCoda("ང", "aN");
        this.addVowelCoda("ངས", "aN");
        this.addVowelCoda("ད", "e");
        this.addVowelCoda("ན", "än");
        this.addVowelCoda("བ", "ab");
        this.addVowelCoda("བས", "ab");
        this.addVowelCoda("མ", "am");
        this.addVowelCoda("མས", "am");
        this.addVowelCoda("ལ", "äl");
        this.addVowelCoda("འི", "e");
        this.addVowelCoda("འིའོ", "aio");
        this.addVowelCoda("འོ", "ao");
        this.addVowelCoda("འང", "aN");
        this.addVowelCoda("འམ", "am");
        this.addVowelCoda("ར", "ar");
        this.addVowelCoda("ས", "e");
        this.addVowelCoda("ི", "i");
        this.addVowelCoda("ིག", "ig");
        this.addVowelCoda("ིགས", "ig");
        this.addVowelCoda("ིང", "iN");
        this.addVowelCoda("ིངས", "iN");
        this.addVowelCoda("ིད", "i");
        this.addVowelCoda("ིན", "in");
        this.addVowelCoda("ིབ", "ib");
        this.addVowelCoda("ིབས", "ib");
        this.addVowelCoda("ིམ", "im");
        this.addVowelCoda("ིམས", "im");
        this.addVowelCoda("ིལ", "il");
        this.addVowelCoda("ིའི", "i");
        this.addVowelCoda("ིའིའོ", "io");
        this.addVowelCoda("ིའོ", "io");
        this.addVowelCoda("ིའང", "iaN");
        this.addVowelCoda("ིའམ", "iam");
        this.addVowelCoda("ིར", "ir");
        this.addVowelCoda("ིས", "i");
        this.addVowelCoda("ུ", "u");
        this.addVowelCoda("ུག", "ug");
        this.addVowelCoda("ུགས", "ug");
        this.addVowelCoda("ུང", "uN");
        this.addVowelCoda("ུངས", "uN");
        this.addVowelCoda("ུད", "u");
        this.addVowelCoda("ུན", "un");
        this.addVowelCoda("ུབ", "ub");
        this.addVowelCoda("ུབས", "ub");
        this.addVowelCoda("ུམ", "um");
        this.addVowelCoda("ུམས", "um");
        this.addVowelCoda("ུལ", "ul");
        this.addVowelCoda("ུའི", "u");
        this.addVowelCoda("ུའིའོ", "uio");
        this.addVowelCoda("ུའོ", "uo");
        this.addVowelCoda("ུའང", "uaN");
        this.addVowelCoda("ུའམ", "uam");
        this.addVowelCoda("ུར", "ur");
        this.addVowelCoda("ུས", "u");
        this.addVowelCoda("ེ", "e");
        this.addVowelCoda("ེག", "eg");
        this.addVowelCoda("ེགས", "eg");
        this.addVowelCoda("ེང", "eN");
        this.addVowelCoda("ེངས", "eN");
        this.addVowelCoda("ེད", "e");
        this.addVowelCoda("ེན", "en");
        this.addVowelCoda("ེབ", "eb");
        this.addVowelCoda("ེབས", "eb");
        this.addVowelCoda("ེམ", "em");
        this.addVowelCoda("ེམས", "em");
        this.addVowelCoda("ེལ", "el");
        this.addVowelCoda("ེའི", "e");
        this.addVowelCoda("ེའིའོ", "eio");
        this.addVowelCoda("ེའོ", "eo");
        this.addVowelCoda("ེའང", "eaN");
        this.addVowelCoda("ེའམ", "eam");
        this.addVowelCoda("ེར", "er");
        this.addVowelCoda("ེས", "e");
        this.addVowelCoda("ོ", "o");
        this.addVowelCoda("ོག", "og");
        this.addVowelCoda("ོགས", "og");
        this.addVowelCoda("ོང", "oN");
        this.addVowelCoda("ོངས", "oN");
        this.addVowelCoda("ོད", "o");
        this.addVowelCoda("ོན", "on");
        this.addVowelCoda("ོབ", "op");
        this.addVowelCoda("ོབས", "op");
        this.addVowelCoda("ོམ", "om");
        this.addVowelCoda("ོམས", "om");
        this.addVowelCoda("ོལ", "ol");
        this.addVowelCoda("ོའི", "oj");
        this.addVowelCoda("ོའིའོ", "oio");
        this.addVowelCoda("ོའོ", "o");
        this.addVowelCoda("ོའང", "oaN");
        this.addVowelCoda("ོའམ", "oam");
        this.addVowelCoda("ོར", "or");
        this.addVowelCoda("ོས", "o");
        this.addVowelCoda("འུ", "au");
        this.addVowelCoda("འུའི", "au");
        this.addVowelCoda("འུའིའོ", "auio");
        this.addVowelCoda("འུའོ", "auo");
        this.addVowelCoda("འུའང", "auaN");
        this.addVowelCoda("འུའམ", "auam");
        this.addVowelCoda("འུར", "aur");
        this.addVowelCoda("འུས", "au");
        this.addVowelCoda("ིའུ", "iu");
        this.addVowelCoda("ིའུའི", "iui");
        this.addVowelCoda("ིའུའིའོ", "iuio");
        this.addVowelCoda("ིའུའོ", "iuo");
        this.addVowelCoda("ིའུའང", "iuaN");
        this.addVowelCoda("ིའུའམ", "iuam");
        this.addVowelCoda("ིའུར", "iur");
        this.addVowelCoda("ིའུས", "iu");
        this.addVowelCoda("ུའུ", "u");
        this.addVowelCoda("ུའུའི", "ui");
        this.addVowelCoda("ུའུའིའོ", "uio");
        this.addVowelCoda("ུའུའོ", "uo");
        this.addVowelCoda("ུའུའང", "uaN");
        this.addVowelCoda("ུའུའམ", "uam");
        this.addVowelCoda("ུའུར", "ur");
        this.addVowelCoda("ུའུས", "u");
        this.addVowelCoda("ེའུ", "eu");
        this.addVowelCoda("ེའུའི", "eu");
        this.addVowelCoda("ེའུའིའོ", "euio");
        this.addVowelCoda("ེའུའོ", "euo");
        this.addVowelCoda("ེའུའང", "euaN");
        this.addVowelCoda("ེའུའམ", "euam");
        this.addVowelCoda("ེའུར", "eur");
        this.addVowelCoda("ེའུས", "eu");
        this.addVowelCoda("ོའུ", "ou");
        this.addVowelCoda("ོའུའི", "oui");
        this.addVowelCoda("ོའུའིའོ", "ouio");
        this.addVowelCoda("ོའུའོ", "ouo");
        this.addVowelCoda("ོའུའང", "ouaN");
        this.addVowelCoda("ོའུའམ", "ouam");
        this.addVowelCoda("ོའུར", "our");
        this.addVowelCoda("ོའུས", "ou");
        
        this.sktPhonetic = new HashMap<>();
        this.addSkt('ཀ', "g");
        this.addSkt('ཁ', "g");
        this.addSkt('ག', "g");
        this.addSkt('ང', "N");
        this.addSkt('ཅ', "c");
        this.addSkt('ཆ', "c");
        this.addSkt('ཇ', "c");
        this.addSkt('ཉ', "Y");
        this.addSkt('ཐ', "d");
        this.addSkt('ཏ', "d");
        this.addSkt('ད', "d");
        this.addSkt('ན', "n");
        this.addSkt('པ', "b");
        this.addSkt('ཕ', "b");
        this.addSkt('བ', "b");
        this.addSkt('མ', "m");
        this.addSkt('ཙ', "T");
        this.addSkt('ཚ', "T");
        this.addSkt('ཛ', "T");
        this.addSkt('ཝ', "b");
        this.addSkt('ཞ', "S");
        this.addSkt('ཟ', "s");
        this.addSkt('འ', "");
        this.addSkt('ཡ', "y");
        this.addSkt('ར', "r");
        this.addSkt('ལ', "l");
        this.addSkt('ཤ', "S");
        this.addSkt('ཥ', "S");
        this.addSkt('ས', "s");
        this.addSkt('ཧ', "");
        this.addSkt('ཨ', "");
        this.addSkt('ཪ', "r");
        this.addSkt('ཱ', "");
        this.addSkt('ི', "i");
        this.addSkt('ུ', "u");
        this.addSkt('ེ', "e");
        this.addSkt('ཻ', "e");
        this.addSkt('ོ', "o");
        this.addSkt('ཽ', "o");
        this.addSkt('ཾ', "n");
        this.addSkt('ཿ', "");
        this.addSkt('ྀ', "i");
        this.addSkt('ྂ', "n");
        this.addSkt('ྃ', "n");
        this.addSkt('྄', "");
        this.addSkt('ྐ', "g");
        this.addSkt('ྑ', "g");
        this.addSkt('ྒ', "g");
        this.addSkt('ྔ', "N");
        this.addSkt('ྕ', "c");
        this.addSkt('ྖ', "c");
        this.addSkt('ྗ', "c");
        this.addSkt('ྙ', "Y");
        this.addSkt('ྟ', "d");
        this.addSkt('ྠ', "d");
        this.addSkt('ྡ', "d");
        this.addSkt('ྣ', "n");
        this.addSkt('ྤ', "b");
        this.addSkt('ྥ', "b");
        this.addSkt('ྦ', "b");
        this.addSkt('ྨ', "m");
        this.addSkt('ྩ', "T");
        this.addSkt('ྪ', "T");
        this.addSkt('ྫ', "T");
        this.addSkt('ྭ', "");
        this.addSkt('ྮ', "S");
        this.addSkt('ྯ', "s");
        this.addSkt('ྰ', "");
        this.addSkt('ྱ', "y");
        this.addSkt('ྲ', "r");
        this.addSkt('ླ', "l");
        this.addSkt('ྴ', "S");
        this.addSkt('ྵ', "S");
        this.addSkt('ྶ', "s");
        this.addSkt('ྷ', "");
        this.addSkt('ྸ', "");
        this.addSkt('ྺ', "b");
        this.addSkt('ྻ', "y");
        this.addSkt('ྼ', "r");
    }

}
